### ISSUE TITLE
[bug] Resetting of value to non-zero when burning last token

### ISSUE THREAD

**Issue by mg6maciej** [0xcert/ethereum-erc721#105]
When burn is called on the last token, code in `removeNFToken` will not clear `idToOwnerIndex` for it.
Order of these statements should be changed, but even better to use check for last token mentioned in previous issue #104.
```
    idToOwnerIndex[_tokenId] = 0;
    idToOwnerIndex[lastToken] = tokenToRemoveIndex;
```

**Comment by MoMannn** [comment]
I'm kind of not sure which approach would be better here.
 
I would change the order because it is unlikely that an event of burning all the tokens happens often if at all so the check mentioned it #104 would consume more gas overall. 

But on the other hand if there would be contract that constantly burns all the tokens the gas price will be much higher for it. 

@mg6maciej @xpepermint @lknix Thoughts?

**Comment by lknix** [comment]
I'd go for simplicity (changing the order) unless gas difference justifies it.

**Comment by lknix** [comment]
@mg6maciej current fix: https://github.com/0xcert/ethereum-erc721/pull/110
