### ISSUE TITLE
Reconsider overridability of _transfer

### ISSUE THREAD

**Issue by fulldecent** [0xcert/ethereum-erc721#153]
Example use case:

https://github.com/fourpark/contracts/blob/7aaaa66f9d53632ec69bc76f3d09fab977b8962e/contracts/FourPark.sol#L61-L87

This is probably NOT how we want people overriding transfers!

**Comment by MoMannn** [comment]
Why not? It is their choice..

**Comment by fulldecent** [comment]
Did you notice the security vulnerability in that example?

**Comment by MoMannn** [comment]
I don't believe I did. Can you elaborate?

**Comment by fulldecent** [comment]
They forgot to reimplement `safeTransferFrom` with four arguments.

Their use is adding transfer restrictions. Because of this oversight, transfers performed using `safeTransferFrom` with four arguments will succeed without checking the custom restriction.

I think the preferred way to do this might be to subclass and reimplement _transfer with the new restriction. This is DRY.

**Comment by MoMannn** [comment]
Ok, I see that. 

I completely misunderstood you. The way they are overriding is not how we want to. `_transfer` function should be internal and they should be able to override only that function to achieve what they need. This must have been overlooked here since the monolith version has it as internal. Will fix.

**Comment by MoMannn** [comment]
https://github.com/0xcert/ethereum-erc721/pull/154

**Comment by fulldecent** [comment]
Confirmed fixed in new branch
