### ISSUE TITLE
Safe math use return names

### ISSUE THREAD

**Issue by fulldecent** [0xcert/ethereum-erc721#161]
We should name the return values because they are relevant in NatSpec.

https://solidity.readthedocs.io/en/develop/abi-spec.html

Priority low
Target 2.1.0

**Comment by MoMannn** [comment]
To be honest I'm quite confused about the policy of naming return values. What is the specific logic behind it? I was looking at https://github.com/ethereum/EIPs/blob/master/EIPS/eip-721.md the Metadata extensions. Name and symbol have return names defined while tokenURI and every other return does not. Why is that? Should we use names everywhere or nowhere? We are currently somewhere in the middle since we are strictly following the standard.

**Comment by fulldecent** [comment]
EIP-721 is inconsistent and in bad need of a style guide. If we can get a good Solidity-wide style guide then updating 721 final would be in scope. (Other changes are already scheduled based on Solidity changes.)

The value of return naming is that it is actually included in the JSON ABI schema. Returning `{"name": "difference"}` is better than `{"name": ""}`.

**Comment by MoMannn** [comment]
Thank you for clarifying. I guess we should change this for all of our stuff but still leave erc721 methods alone until the changes are made in the standard itself?

**Comment by MoMannn** [comment]
#174

**Comment by fulldecent** [comment]
Yes and yes. 

I’ll work on getting a stronger Solidity-wide style guide, then updating 721 and other ERCs
